### ISSUE TITLE
下载了不知道怎么创建selenium 库 和怎么使用

### ISSUE THREAD

**Issue by qq1599597527** [Sduby22/Auto-AnswerXinLinian-R#1]
下载了不知道怎么创建selenium 库 和怎么使用，老哥能方便教一下吗，有偿，谢谢

**Comment by Sduby22** [comment]
你好，在使用python脚本之前最好稍微有点python基础，否则会遇到许多麻烦且恶心的问题
安装selenium库可以尝试
pip install selenium
除此之外你还需要自行配置ChromeDriver之类的东西。

有偿大可不必

bytheway,既然省下了大把学习英语的时间，自己琢磨着解决一点运行上的问题也是可以接受的嘛

**Comment by qq1599597527** [comment]
非常谢谢您，我从昨晚研究到现在，一点基础都没有，遇到了很多麻烦，自己也一 一 解决了，成就感满满的，终于成功了，有一点问题，我想请教您，就是如何调 答题的间隔。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sduby22"<notifications@github.com&gt;; 
发送时间: 2020年5月8日(星期五) 凌晨1:11
收件人: "Sduby22/Auto-AnswerXinLinian-R"<Auto-AnswerXinLinian-R@noreply.github.com&gt;; 
抄送: "a&apos;ゞ网络信息安全顾问"<1599597527@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Sduby22/Auto-AnswerXinLinian-R] 下载了不知道怎么创建selenium 库 和怎么使用 (#1)





 
你好，在使用python脚本之前最好稍微有点python基础，否则会遇到许多麻烦且恶心的问题
 安装selenium库可以尝试
 pip install selenium
 除此之外你还需要自行配置ChromeDriver之类的东西。
 
有偿大可不必
 
bytheway,既然省下了大把学习英语的时间，自己琢磨着解决一点运行上的问题也是可以接受的嘛

**Comment by qq1599597527** [comment]
非常谢谢您，我从昨晚研究到现在，一点基础都没有，遇到了很多麻烦，自己也一 一 解决了，成就感满满的，终于成功了，有一点问题，我想请教您，就是如何调 答题的间隔。

**Comment by Sduby22** [comment]
恭喜，我还以为只有我们学校可以用..
关于答题的间隔，我本来想搞自定义答题时间的，但是我太懒了
具体实现其实会非常简单
在main文件的开头import time
然后time库里有个time.sleep()函数
是睡眠x秒的函数，你可以思考一下这个函数放在哪里可以实现你的需求
我就懒得写了xd

**Comment by qq1599597527** [comment]
嗯，的确是 sleep（x）函数修改了就可以，但是我现在想到一个更好的方法，即使做完了也可以，请问前辈 能否去除 自动提交的函数呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sduby22"<notifications@github.com&gt;; 
发送时间: 2020年5月8日(星期五) 凌晨1:27
收件人: "Sduby22/Auto-AnswerXinLinian-R"<Auto-AnswerXinLinian-R@noreply.github.com&gt;; 
抄送: "a&apos;ゞ网络信息安全顾问"<1599597527@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Sduby22/Auto-AnswerXinLinian-R] 下载了不知道怎么创建selenium 库 和怎么使用 (#1)





 
恭喜，我还以为只有我们学校可以用..
 关于答题的间隔，我本来想搞自定义答题时间的，但是我太懒了
 具体实现其实会非常简单
 在main文件的开头import time
 然后time库里有个time.sleep()函数
 是睡眠x秒的函数，你可以思考一下这个函数放在哪里可以实现你的需求
 我就懒得写了xd

**Comment by qq1599597527** [comment]
嗯，的确是 sleep（x）函数修改了就可以，但是我现在想到一个更好的方法，即使做完了也可以，请问前辈 能否去除 自动提交的函数呢？

**Comment by qq1599597527** [comment]
我觉得做的快也没有关系，主要是 控制住提交的时间就OK了，做的快这个也没事

**Comment by Sduby22** [comment]
在main.py line153行有注释，那里是自动提交的代码
把下面那个if整个删掉(154~158)就不会自动提交了

qq1599597527 <notifications@github.com> 于 2020年5月8日周五 01:31写道：

**Comment by qq1599597527** [comment]
好的，非常感谢前辈，不知道该如何答谢您。

**Comment by Sduby22** [comment]
不用谢，喜欢的话可以帮我点个star~

qq1599597527 <notifications@github.com> 于 2020年5月8日周五 01:34写道：
